import os
import shutil
import sys
from pathlib import Path

os.environ.setdefault("MPLBACKEND", "Agg")  # before any matplotlib import: tests never open a window
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))  # the course scripts are importable modules

import numpy as np
import pytest

from zero2fsd.car.runner import Telemetry


@pytest.fixture
def make_tel():
    """Hand-built telemetry: `make_tel(lat=[...], progress=[...])`, every other array zero unless given."""

    def make(lat, progress, route_length=200.0, scenario="straight", **arrays):
        n = len(lat)
        zeros = {name: np.zeros(n) for name in ("x", "y", "yaw", "speed", "steer", "accel", "head_err", "est_offset", "est_heading")}
        fields = {
            "t": np.arange(n) * 0.05, **zeros, "lat": np.asarray(lat, float), "progress_m": np.asarray(progress, float),
            "est_valid": np.ones(n, bool), "off_road": np.zeros(n, bool),
        }
        fields.update({k: np.asarray(v) for k, v in arrays.items()})
        return Telemetry(**fields, scenario=scenario, completed=False, route_length=route_length)

    return make


@pytest.fixture
def mini_repo(tmp_path):
    """A writable copy of the one-unit fixture repo (sources only: no lab.ipynb, no figures, no dist)."""
    root = tmp_path / "repo"
    shutil.copytree(Path(__file__).parent / "fixtures" / "mini_repo", root)
    return root


@pytest.fixture
def built_repo(mini_repo):
    """The fixture repo with its notebook and figures generated by the real scripts."""
    import build_labs
    import make_figures

    assert build_labs.main(["--root", str(mini_repo)]) == 0 and make_figures.main(["--root", str(mini_repo)]) == 0
    return mini_repo
